#+TITLE: Fn Special Forms Documentation
#+OPTIONS: num:2

* Design Philosophy

Fn values consistency, extensibility, zero-cost abstraction, and
expressiveness.

Consistency means that the syntax and API should adhere to a shared set of
patterns wherever possible. Consistency brings many benefits, making the
language easier to parse and process for both humans and tools, while also
lending to its aesthetic appeal.

Extensible languages make it easy for programmers to customize and enhance
their tools as well as the language itself. In Fn, this is achieved with the
type system and metaprogramming facilities.

Zero-cost abstraction is the capability to write code which more closely models
the problem domain without incurring any runtime performance costs (compared to
less abstract code). In contrast to most dialects of Lisp, Fn provides a static
algebraic type system which allows programmers to write polymorphic code
without incurring the overheads of runtime type checking and virtual method
dispatch. Additionally, macros enable sophisticated compile-time processing in
order to generate efficient code.

Expressiveness refers to the friendliness of the language toward creating good
models of a problem domain. Fn attempts to combine expressiveness with
zero-cost abstraction by carefully selecting a set of primitives which balance
efficiency with expressive power.

Fn strives to provide a programming experience which provides more control and
performance than high-level languages like Clojure and Python, without
sacrificing any expressive power. Even more importantly, Fn is a unique and
opinionated language which I hope will be a joy to use.

* The Toplevel

Fn code is organized into source files. The outermost scope of a file is called
the *toplevel*. When a file is evaluated, all toplevel expressions are executed.
Toplevel expressions within a file are automatically collected and reordered by
the interpreter to enable out-of-order definition and mutual recursion.

The following special forms are legal at the toplevel:
#+begin_src
import require
fn macro method
let
do when
do-inline
struct tagged-union variant
#+end_src
Macros are also legal at the toplevel, provided they ultimately expand into one
of the above expressions.

As mentioned above, toplevel expressions may be reordered by the interpreter. It
is however guaranteed that ~do~ and ~when~ blocks will be executed in the order
in which they occur in the file.

* Namespaces

Fn code is organized into namespaces. Namespaces consist of an identifier and a
collection of global variables, i.e. a map from names to values.

The current namespace can be set using a toplevel ~namespace~ declaration. The
~namespace~ declaration has syntax
#+begin_src
(namespace full.namespace.name)
#+end_src
and sets the namespace for all code below that declaration (until the next
namespace declaration).

Once the code for a namespace has been loaded, the variables in that namespace
can be accessed using the full namespace name by prepending a dot:
#+begin_src fn
.full.namespace.name.var-name
; e.g.
(namespace my.ns)
(let my-var 42)
; now can acces my-var from any namespace as
.my.ns.my-var
#+end_src

This syntax can be shortened substantially by importing the other namespace into
the current one using ~import~:
#+begin_src fn
(import full.namespace.name)
(import full.namespace.name :as short-name)

; continuation of above example

; by default the short name is the token after the last dot
(import my.ns)
ns.my-var

; short name can be set manually
(import my.ns :as foo)
foo.my-var
#+end_src

~import~ may only be used at the toplevel.

In addition, the special form ~import-from~ may be used to import variables
directly from an external namespace into the current one, without needing a
prefix.
#+begin_src fn
(import-from full.namespace.name vars...)

; e.g.
(import my.ns my-var)
my-var
#+end_src

* Variables and Blocks

Fn employs the usual lexical scope for its variables. At this time dynamic
variables are not supported, although this may change in the future.

Variables in Fn are generally introduced with the ~let~ or ~fn~ special forms. At
the toplevel, these create global variables. Global variables are accessible
from anywhere in the program.

A *block* in Fn is a sequence of expressions wrapped in its own lexical
environment. Blocks occur in the bodies of functions and ~do~ forms, as well as in
the clauses of a ~when~ expression.

When ~let~ appears in a block, it binds one or more local variables for the rest
of the block. These bindings are not recursive by default, which is to say that
the value of the variable cannot refer to itself by name for e.g. defining
recursive functions. Including the ~:rec~ modifier keyword with a variable
definition will make its name available within its own value form and all other
value forms being bound within the same let expression. See [[let]] for more
information.

Bindings made with ~fn~ are recursive by default, which is to say that the
function can call itself recursively by name.

Local variables usually only live until the end of the block in which they are
introduced, but their lifetime may be extended by capturing them with a
function.

* Types

Fn supports a variety of built-in types. We distinguish between primitive types,
array types, virtual types, and user-defined types.

** Primitive Types

A primitive type is one of the following:
#+begin_src fn
I8 I16 I32 I64
U8 U16 U32 U64
F32 F64
Bool
Int
String
#+end_src
Primitive types are built-in and indivisible. Integer types are automatically
promoted to larger integer types when necessary. Casting to a smaller bit width
requires an explicit command.

Virtual types represent values that conform to a specific interface, but whose
exact concrete type may not be known until runtime.

* Functions and Methods

Functions and methods are callable chunks of code which may be parameterized
over a set of arguments. Function and method bodies are *blocks*, which are
sequences of expressions that are evaluated in order. See [[Control Flow]] for more
on blocks.

Functions are created with the ~fn~ special form (see [[fn]] for usage). Functions may
capture variables from their lexical environment.

* Pattern Matching

* Special Forms
** defer
*** Syntax

(*defer* _block_)

*** Arguments and Values

- _block_ :: A sequence of expressions to defer.

*** Description

The ~defer~ special form schedules expressions to be executed when the current
block exits. This is useful for ensuring that certain cleanup tasks are
performed, such as closing files or releasing resources.

*** Examples

#+begin_src fn
(do
  (let file (io.open "example.txt" "r"))
  (defer (file :close))
  (println (file :read)))
#+end_src

** do
*** Syntax

(*do* _block_)
(*do* *:name* _name_ _block_)

*** Arguments and Values

- _name_ :: An optional name for the block.
- _block_ :: A sequence of expressions to execute.

*** Description

The ~do~ special form introduces a new block. The expressions in the block are
evaluated in order, and the value of the last expression is returned.
Optionally, a name can be provided for the block, which can be used with the
~return~ special form to return early with the provided value.

*** Examples

#+begin_src fn
(do (println "Calculating...") (+ x y))
#+end_src

** do-inline
*** Syntax

(*do-inline* _body_)

*** Arguments and Values

- _body_ :: A sequence of expressions to execute.

*** Description

The ~do-inline~ special form behaves like the ~do~ form, but instead of creating a
new block, it causes the expressions to be executed as if they were placed
directly in the surrounding block. This is intended for use by macro authors to
allow macros to introduce local variables.

*** Examples

#+begin_src fn
(do-inline (let x 5) (let y 3) (+ x y))
#+end_src

** fn
*** Syntax

(*fn* _name_ ( _args_ ) [ _return-type_ ] _block_)
(*fn* ( _args_ ) [ _return-type_ ] _block_)

*** Arguments and Values

- _name_ :: Optional name for the function.
- _args_ :: List of arguments to the function, including type annotations for each
  one.
- _return-type_ :: Type expression indicating the return type.
- _block_ :: The body of the function.

*** Description

The ~fn~ special form defines a function with an optional name, a list of
parameters with type annotations, an optional return type, and a body. If the
name is provided and the ~fn~ form appears within a block, the function is
assigned to a variable with that name. If no return type is provided, it will be
inferred from the body.

*** Examples

#+begin_src fn
(fn add (x [Int] y [Int]) [Int] (+ x y))
(fn (x [Int] y [Int]) [Int] (+ x y))
#+end_src

** if
*** Syntax

(*if* _test_ _then_)
(*if* _test_ _then_ _else_)

*** Arguments and Values

- _test_ :: The test expression.
- _then_ :: The expression to evaluate if the test is true.
- _else_ :: The expression to evaluate if the test is false. Optional.

*** Description

The if special form provides conditional branching based on the test expression.
If the test is true, the then expression is evaluated, otherwise the else
expression is evaluated if provided. If no else expression is provided and the
test is false, Nil is returned.

*** Examples

#+begin_src fn
(if (> x y) "x is greater" "x is not greater")
#+end_src

** let
*** Syntax

(*let* _pattern_ _value_ _modifiers_)
(*let* _pattern_ _value_ [ _type_ ] _modifiers_)
(*let* _let-specs_...)

*** Arguments and Values
- _pattern_ :: A pattern or variable name.
- _value_ :: The value to assign to the pattern.
- _modifiers_ :: Zero or more keywords used to change the semantics of the
  variable. Options include ~:mut~ to indicate that the variable is mutable and
  ~:rec~ for support for mutually recursive bindings.
- _type_ :: An optional type expression indicating the type of the value. If this
  is not provided, the type will be inferred.
- _let-specs_ :: One or more pattern/value pairs (optionally with type and/or
  modifiers).

*** Description

The let special form binds one or more variables to values in the current block.
Optional type annotations may follow the value forms. The binding is visible in
the remainder of the current block.

*** Examples

#+begin_src fn
(let x 5 [Int])
(let x 5 y 6)
#+end_src

** macro
*** Syntax

(*macro* _name_ ( _args_ ) _body_)

*** Arguments and Values
- _name_ :: The name of the macro.
- _args_ :: List of arguments to the macro.
- _body_ :: The body of the macro.

*** Description

The macro special form defines a macro with a name, a list of arguments, and a
body. Macros are expanded at compile time, allowing for powerful code generation
and abstraction capabilities.

*** Examples

#+begin_src fn
; todo
#+end_src

** method
*** Syntax

(*method* _name_ ( _args_ ) [ _return-type_ ] _body_)

*** Arguments and Values

- _name_ :: The name of the method.
- _args_ :: List of arguments to the method, including a self argument and type
  annotations for each argument.
- _return-type_ :: Type expression indicating the return type.
- _body_ :: The body of the method.

*** Description

The method special form defines a method with a name, a list of arguments
(including a self argument representing the object on which the method is
called), an optional return type, and a body. The method is bound to the struct
specified by the self argument type.

*** Examples

#+begin_src fn
(struct Point ()
  x [Int]
  y [Int])

(method distance (self [Point] other [Point]) [Float]
  (let dx (- (other :x) (self :x))
       dy (- (other :y) (self :y)))
  (sqrt (+ (* dx dx) (* dy dy))))
#+end_src

** return
*** Syntax

(*return*)
(*return* _value_)
(*return* _value_ _name_)

*** Arguments and Values

- _value_ :: Optional return value. If none is provided, returns ~Nil~.
- _name_ :: Name of the block to return from. If none is provided, return from the
  current function.

*** Description

The return special form is used to return a value from a function or a named
block early. If a value is provided, it will be returned; otherwise, Nil is
returned. If a name is provided, the return will be from the named block;
otherwise, it returns from the innermost function.

*** Examples

#+begin_src fn
(return)
(return 42)
(return 42 my-block)
#+end_src

** struct
*** Syntax

(*struct* _name_ () _fields-and-types_)
(*struct* _name_ (_type-parameters_) _fields-and-types_)

*** Arguments and Values

- _name_ :: The name of the struct.
- _type-parameters_ :: Optional list of type parameters.
- _fields-and-types_ :: List of field names and their types.

*** Description

The struct special form defines a new struct type with a specified name,
optional type parameters, and a list of fields and their types. Structs are used
to create custom data structures that can be used throughout the program.

*** Examples

#+begin_src fn
(struct Point ()
  x [Int]
  y [Int])
(struct Pair (A B)
  first [A]
  second [B])
#+end_src

** switch
*** Syntax

(*switch* _value_ _clauses_)

*** Arguments and Values

- _value_ :: The value to be matched against.
- _clauses_ :: A sequence of clauses, each starting with a :case keyword followed
  by a pattern and one or more expressions to evaluate.

*** Description

The switch special form provides a pattern matching mechanism for branching
based on the value provided. Each clause starts with the :case keyword, followed
by a pattern and an expression to evaluate if the pattern matches the value. The
first matching clause's expression will be evaluated and returned.

*** Examples

#+begin_src fn
(variant Color () Red Green Blue)

(fn describe-color (color [Color]) [String]
  (switch color
    :case Red "This is the color red."
    :case Green "This is the color green."
    :case Blue "This is the color blue."))

(describe-color Red) ; Output: "This is the color red."
(describe-color Green) ; Output: "This is the color green."
(describe-color Blue) ; Output: "This is the color blue."
#+end_src

** tagged-union
*** Syntax

(*tagged-union* _name_ () _types_)
(*tagged-union* _name_ (_type-parameters_) _types_)

*** Arguments and Values

- _name_ :: The name of the tagged union.
- _type-parameters_ :: Optional sequence of type parameters.
- _types_ :: Sequence of types that make up the union.

*** Description

The tagged-union special form defines a new tagged union type with a specified
name, optional type parameters, and a list of types that make up the union.
Tagged unions are used to represent values that can be one of several different
types.

*** Examples

#+begin_src fn
(tagged-union Value () Int Float String)
#+end_src

** variant
*** Syntax

(*variant* _name_ () _constructors_)
(*variant* _name_ (_type-parameters_) _constructors_)

*** Arguments and Values

- _name_ :: The name of the variant.
- _type-parameters_ :: Optional list of type parameters.
- _constructors_ :: Sequence of constructor names and their argument types.

*** Description

The variant special form defines a new variant type with a specified name,
optional type parameters, and a list of constructor names and their argument
types. Variants are used to create custom sum types that represent a choice
between several different constructors.

*** Examples

#+begin_src fn
(variant Color () Red Green Blue)
(variant Option (A)
  (Some [A])
  None)
#+end_src

** when
*** Syntax

(*when* _condition_ _body-and-other-clauses_)

*** Arguments and Values

- _condition_ :: The test expression.
- _body-and-other-clauses_ :: A sequence of expressions and additional clauses.

*** Description

The when special form provides conditional branching based on the test
expression. If the test is true, the body of code is executed. Additional
clauses may be introduced within the when expression using the keywords ~:elif~,
~:else~, and ~:elif-match~ to begin new clauses.

*** Examples

#+begin_src fn
(when (> x y)
  (println "x is greater")
  :else
  (println "y is greater"))
#+end_src

* Namespace ~fn.builtin~

** function: list

** function: map

** macro: partial

*** Declaration

*** Arguments

*** Result

** function: print

** function: println

** function: readln

*** Declaration

#+begin_src fn
(fn readln ((from .fn.io.stdin) [.fn.io.File]) [! String IOError])
#+end_src

*** Arguments

- from :: A file handle

*** Result

The String that was read, or an IOError.

** macro: apply

#+begin_src fn
(macro apply (fun & args-and-arg-seq))
#+end_src

** macro: compose

#+begin_src fn
(macro compose (f1 & fs))
#+end_src

** function: compose2

#+begin_src fn
(fn compose2 (f1 [Fn (b) a] f2 [Fn (c) b]) [Fn (c) a])
#+end_src

** macro: fmt

#+begin_src fn
(macro fmt (fmt-str))
#+end_src

** function: list

** macro: printf

** function: vec

** function: filter

** function: maybe

** function: 

* Built-in Persistent Containers

Fn comes with out of the box support for persistent vectors, lazy immutable
lists, and persistent hash maps (HAMTs). Mutable arrays and hash tables are also
provided.
